name: 'postgres_postgres_small_aggregate'
description: 'Pipeline sync for aggregation'

# global column definition that will be used everywhere. Every stage with columns field will inherit these columns.
# This is an optional field. If not provided, every stage will have to define its own columns.
max_concurrent_partitions: 1
hash_algo: 'md5_sum_hash'
strategies:
  # Delta sync every 15 minutes
  - name: 'delta'
    type: 'delta'
    default: true
    primary_partitions:
      - column: 'updated_at'
        step: '7200'  # 2 hours
    secondary_partitions:
      - column: 'updated_at'
        step: '1800'  # 30 minutes
    max_concurrent_partitions: 1
    enabled: true
    cron: '*/15 * * * *'  # Every 15 minutes
    page_size: 10
    use_pagination: true
    # use_sub_partition: false
  
  # Hash sync every 2 hours
  - name: 'hash'
    type: 'hash'
    default: true
    enabled: true
    primary_partitions:
      - column: 'order_date'
        step: 1
        step_unit: 'month'
        dtype: 'datetime'
      - column: 'user_id'
        step: 50
        dtype: 'integer'
    secondary_partitions:
      - column: 'order_date'
        step: 1
        step_unit: 'day'
        dtype: 'datetime'
      - column: 'user_id'
        step: 5
        dtype: 'integer'
    max_concurrent_partitions: 1
    cron: '0 */2 * * *'  # Every 2 hours
    page_size: 10
    use_pagination: false
    # use_sub_partition: true
    match_row_count: false
  
  # Full sync daily at 3 AM
  - name: 'full'
    type: 'full'
    default: true
    enabled: true
    primary_partitions:
      - column: 'order_date'
        step: 1
        step_unit: 'month'
        dtype: 'datetime'
      - column: 'user_id'
        step: 50
        dtype: 'integer'
    secondary_partitions:
      - column: 'order_date'
        step: 10
        step_unit: 'day'
        dtype: 'datetime'
      - column: 'user_id'
        step: 5
        dtype: 'integer'
    max_concurrent_partitions: 1
    page_size: 10
    cron: '0 3 * * *'  # Daily at 3 AM
    use_pagination: false
    # use_sub_partition: true

backends:
  - name: 'source_backend'
    type: 'postgres'
    datastore_name: 'local_postgres'
    table: 'orders'
    # alias: 'u'
    schema: 'public'
    # join:
    #   - table: 'user_profiles_small'
    #     alias: 'p'
    #     'on': 'u.id = p.user_id'
    #     type: 'left'
    filters: []
    columns:
      - name: 'user_id'
        dtype: 'integer'
      - name: 'amount'
        dtype: 'decimal'
      - name: 'discount'
        dtype: 'decimal'
      - name: 'order_date'
        dtype: 'datetime'

  - name: 'destination_backend'
    type: 'postgres'
    datastore_name: 'local_postgres'
    table: 'user_daily_orders_aggregate'
    schema: 'public_copy'
    columns:
      - name: 'user_id'
        dtype: 'integer'
        unique_column: true
      - name: 'last_order_date'
        dtype: 'datetime'
      - name: 'date'
        dtype: 'date'
        unique_column: true
      - name: 'amount'
        dtype: 'decimal'
      - name: 'discount'
        dtype: 'decimal'
      - name: 'num_orders'
        dtype: 'integer'
      - name: 'checksum_int'
        dtype: 'integer'
        hash_key: true
      - name: 'order_date'
        expr: 'last_order_date'
        dtype: 'datetime'
        virtual: true


stages:
  - name: 'partition_generator'
    type: 'partition'
    enabled: true
    source:
      name: source_backend
      columns:
        - name: 'user_id'
        - name: 'order_date'
    destination:
      name: destination_backend
      columns:
        - name: 'user_id'
        - name: 'order_date'
          expr: 'last_order_date'
  - name: 'change_detection'
    type: 'change_detection'
    enabled: true
    source:
      name: source_backend
    destination:
      name: destination_backend
  - name: 'hash_fetch'
    type: 'data_fetch'
    enabled: true
    source:
      name: source_backend
      columns:
        - name: 'user_id'
        - name: 'last_order_date'
          expr: 'max(order_date)'
        - name: 'num_orders'
          expr: 'count(1)'
        - name: 'amount'
          expr: 'sum(amount)'
        - name: 'discount'
          expr: 'sum(discount)'
        - name: 'date'
          expr: 'CAST(order_date AS DATE)'
      group_by: ['user_id','date']
    destination:
      name: destination_backend
      columns:
        - name: 'user_id'
        - name: 'amount'
        - name: 'discount'
        - name: 'date'
        - name: 'checksum_int'
        - name: 'last_order_date'
        - name: 'num_orders'
  - name: 'hash_batcher'
    type: 'batcher'
    enabled: true
    config:
      target_batch_size: 10
  # - name: 'transformation'
  #   type: 'transform'
  #   enabled: true
  #   transformations:
  #     - columns:
  #         - first_name
  #         - last_name
  #       transform: 'lambda x: x["first_name"]+" "+x["last_name"]'
  #       expr: 'name'
  #       dtype: 'varchar'
  #     - columns:
  #         - uid
  #       transform: 'lambda x: str(x["uid"])'
  #       expr: 'uid'
  #       dtype: 'uuid_text_dash'
  - name: 'populate'
    type: 'populate'
    enabled: true
    destination:
      name: destination_backend
    
    # config:
    #   batch_size: 10000
    #   batch_timeout: 10
    #   batch_timeout_unit: 'seconds'
    #   batch_timeout_value: 10
    #   batch_timeout_unit: 'seconds'
  # - name: 'custom'
  #   type: 'custom'
  #   enabled: true
  #   class_path: 'synctool.enrichment.enrichment_engine.EnrichmentEngine'
  #   config:
  #     transformations:
  #       - columns:
  #           - first_name
  #           - last_name
  #         transform: 'lambda x: x["last_name"].upper()'
  #         dest: 'last_name'
  #         dtype: 'varchar'

